name: CI

on:
  push:
  pull_request:
    paths-ignore:
      - '*/README.md'
      - '*/readme.md'

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main, UPSTREAM_WORKSPACE: "smarc_ds5.rosinstall"}
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}